# FROM mcr.microsoft.com/devcontainers/base:debian
FROM mcr.microsoft.com/devcontainers/ruby
# Set the working directory to /app
WORKDIR /sacapp
# Install Vim
RUN apt-get update && apt-get install -y vim